name: bootstrap_bundle
version: 1.0.0

description: Bundle providing Bootstrap and jQuery in one package. A front-end framework for developing responsive, mobile first projects on the Web.
homepage: https://dev.belin.io/bootstrap.dart
issue_tracker: https://github.com/cedx/bootstrap.dart/issues
repository: https://github.com/cedx/bootstrap.dart

authors:
  - The Bootstrap Authors
  - Twitter, Inc.
  - CÃ©dric Belin <cedric@belin.io>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  grinder: ^0.8.3
  path: ^1.6.2
  sass: ^1.16.1
